const C=window.EF_CONFIG||{};const online=!!(C.SUPABASE_URL&&C.SUPABASE_ANON_KEY);const sb=online?supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];let current=null;
const demoKey='easyfootball_v2_demo';let demo=JSON.parse(localStorage.getItem(demoKey)||'[]');
function toast(x){const t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function view(id){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+id)?.classList.add('active');window.scrollTo(0,0)}
$$('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$('#createBtn').onclick=()=>view('create');$('#createBtn2').onclick=()=>view('create');$('#adminNav').onclick=()=>{view('admin');renderAdmin()};$('#theme').onclick=()=>document.body.classList.toggle('light');
function slug(s){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Math.random().toString(36).slice(2,7)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function createTournament(e){e.preventDefault();const data={name:$('#name').value.trim(),format:$('#format').value,match_minutes:+$('#minutes').value,group_size:+$('#groupSize').value,is_public:$('#public').checked};if(online){const {data:u}=await sb.auth.getUser();if(!u.user){toast('Sign in first');return}const {data:t,error}=await sb.from('tournaments').insert({...data,slug:slug(data.name),admin_id:u.user.id}).select().single();if(error){toast(error.message);return}current=t;openManage(t.id)}else{const t={id:crypto.randomUUID(),slug:slug(data.name),...data,status:'open',players:[],matches:[]};demo.push(t);localStorage.setItem(demoKey,JSON.stringify(demo));current=t;openManage(t.id)}e.target.reset()}
$('#createForm').onsubmit=createTournament;
async function getTournament(id){if(online){const {data,error}=await sb.from('tournaments').select('*').eq('id',id).single();if(error)return null;const [p,m]=await Promise.all([sb.from('players').select('*').eq('tournament_id',id).order('joined_at'),sb.from('matches').select('*').eq('tournament_id',id).order('round_no').order('position')]);return {...data,players:p.data||[],matches:m.data||[]}}return demo.find(t=>t.id===id)}
async function publicTournaments(){if(online){const {data}=await sb.from('tournaments').select('*').eq('is_public',true).order('created_at',{ascending:false});return data||[]}return demo.filter(t=>t.is_public)}
async function renderPublic(){const list=await publicTournaments();$('#publicList').innerHTML=list.map(t=>`<article class="card"><span class="badge">${esc(t.format.toUpperCase())}</span><h3>${esc(t.name)}</h3><p>${esc(t.status)} · ${esc(t.match_minutes)} min</p><div class="row"><button class="primary" onclick="openJoin('${t.id}')">Open</button><button class="ghost" onclick="share('${t.id}')">Share</button></div></article>`).join('');$('#publicEmpty').classList.toggle('hidden',!list.length)}
async function openJoin(id){current=await getTournament(id);if(!current){toast('Tournament not found');return}view('join');$('#joinContent').innerHTML=`<div class="title"><div><small>TOURNAMENT</small><h2>${esc(current.name)}</h2></div><button class="ghost" data-view="tournaments">Back</button></div><div class="panel"><span class="badge">${esc(current.format.toUpperCase())}</span><p>${current.players.length} players · ${current.matches.length} matches</p><h3>Join tournament</h3><form id="joinForm" class="form"><label>Your player name<input id="joinName" required maxlength="40" placeholder="eFootball name"></label><button class="primary" type="submit">Join</button></form><div class="notice">After joining, use this same link to view fixtures and results.</div></div><div id="joinInfo"></div>`;$('#joinForm').onsubmit=async e=>{e.preventDefault();const name=$('#joinName').value.trim();if(!name)return;if(online){const {error}=await sb.from('players').insert({tournament_id:current.id,name});if(error){toast(error.message);return}}else{current.players.push({id:crypto.randomUUID(),name});saveDemo()}toast('Joined!');await openJoin(current.id);renderPublic()};}
function saveDemo(){localStorage.setItem(demoKey,JSON.stringify(demo))}async function share(id){const t=await getTournament(id);const url=location.origin+location.pathname+'#join='+id;navigator.clipboard?.writeText(url);toast('Tournament link copied')}
async function openManage(id){current=await getTournament(id);view('manage');renderManage('overview')}
function renderManage(tab){if(!current)return;const tabs=['overview','matches','standings','players','bracket'];$('#manageContent').innerHTML=`<div class="title"><div><small>TOURNAMENT</small><h2>${esc(current.name)}</h2></div><div><button class="ghost" onclick="share('${current.id}')">🔗 Share</button></div></div><div class="tabs">${tabs.map(x=>`<button class="tab ${tab===x?'active':''}" onclick="renderManage('${x}')">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div><div id="manageBody"></div>`;const b=$('#manageBody');if(tab==='overview')b.innerHTML=`<div class="panel"><h3>Ready to run</h3><p class="hint">Share the link with your players. Players can join, then results can be submitted and confirmed.</p><button class="primary" onclick="openJoin('${current.id}')">Player view</button></div><div class="panel"><b>${current.players.length}</b> players · <b>${current.matches.length}</b> matches · <b>${current.status}</b></div>`;if(tab==='players')renderPlayers(b);if(tab==='matches')renderMatches(b);if(tab==='standings')renderStandings(b);if(tab==='bracket')renderBracket(b)}
function renderPlayers(b){b.innerHTML=`<div class="panel"><h3>Players (${current.players.length})</h3><form id="addPlayer" class="two"><input id="pname" required placeholder="Player name"><button class="primary">Add player</button></form></div><div class="panel">${current.players.map((p,i)=>`<div class="match"><div>${i+1}. ${esc(p.name)}</div><div class="hint">${p.id.slice(0,6)}</div></div>`).join('')}</div>`;$('#addPlayer').onsubmit=async e=>{e.preventDefault();const name=$('#pname').value.trim();if(online){const {error}=await sb.from('players').insert({tournament_id:current.id,name});if(error){toast(error.message);return}}else{current.players.push({id:crypto.randomUUID(),name});saveDemo()}current=await getTournament(current.id);renderManage('players')}}
function renderMatches(b){
 if(!current.matches.length){b.innerHTML='<div class="empty">No fixtures yet. Add players first, then use Generate fixtures.</div>';return}
 let html='<div class="panel"><button class="primary" onclick="generateFixtures()">⚡ Generate / refresh fixtures</button></div>';
 current.matches.forEach(m=>{const h=current.players.find(p=>p.id===m.home_player_id)?.name||'TBD',a=current.players.find(p=>p.id===m.away_player_id)?.name||'TBD';html+=`<div class="panel match"><div class="team">${esc(h)}</div><div class="score">${m.status==='confirmed'?m.home_score+' - '+m.away_score:'VS'}</div><div class="team">${esc(a)}</div></div><div class="panel"><button class="ghost" onclick="submitResult('${m.id}')">${m.status==='confirmed'?'Edit result':'Submit result'}</button>${m.status==='pending'?` <button class="primary" onclick="confirmResult('${m.id}')">Confirm</button>`:''}</div>`});b.innerHTML=html}
function standings(){const s={};current.players.forEach(p=>s[p.id]={p,w:0,d:0,l:0,gf:0,ga:0,pts:0});current.matches.filter(m=>m.status==='confirmed').forEach(m=>{if(!s[m.home_player_id]||!s[m.away_player_id])return;let h=s[m.home_player_id],a=s[m.away_player_id];h.gf+=m.home_score;h.ga+=m.away_score;a.gf+=m.away_score;a.ga+=m.home_score;if(m.home_score>m.away_score){h.w++;h.pts+=3;a.l++}else if(m.home_score<m.away_score){a.w++;a.pts+=3;h.l++}else{h.d++;a.d++;h.pts++;a.pts++}});return Object.values(s).sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf)}
function renderStandings(b){let rows=standings().map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.p.name)}</td><td>${x.w}</td><td>${x.d}</td><td>${x.l}</td><td>${x.gf-x.ga}</td><td><b>${x.pts}</b></td></tr>`).join('');b.innerHTML=`<div class="panel"><table><thead><tr><th>#</th><th>Player</th><th>W</th><th>D</th><th>L</th><th>GD</th><th>PTS</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function renderBracket(b){const rounds={};current.matches.filter(m=>m.stage==='knockout').forEach(m=>(rounds[m.round_no]??=[]).push(m));b.innerHTML=`<div class="bracket">${Object.entries(rounds).map(([r,ms])=>`<div class="round"><h4>Round ${r}</h4>${ms.map(m=>{const h=current.players.find(p=>p.id===m.home_player_id)?.name||'TBD',a=current.players.find(p=>p.id===m.away_player_id)?.name||'TBD';return `<div class="fixture"><div><span>${esc(h)}</span><b>${m.home_score??'-'}</b></div><div><span>${esc(a)}</span><b>${m.away_score??'-'}</b></div></div>`}).join('')}</div>`).join('')||'<div class="empty">Generate a knockout tournament to see the bracket.</div>'}</div>`}
function renderAdmin(){if(!online){$('#adminContent').innerHTML='<div class="notice">Demo mode is active. Add your Supabase URL and anon key to <b>config.js</b> to enable accounts and shared tournaments.</div>';return}$('#adminContent').innerHTML='<div class="panel"><p>Sign in to create and manage your tournaments.</p><button class="primary" id="emailLogin">Send magic-link login</button><input id="email" placeholder="your@email.com" style="margin:10px 0;padding:12px;width:100%;background:#07130d;color:white;border:1px solid var(--line);border-radius:10px"></div>';$('#emailLogin').onclick=async()=>{const email=$('#email').value.trim();const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});toast(error?error.message:'Check your email')};}
async function submitResult(id){const m=current.matches.find(x=>x.id===id);if(!m)return;const hs=prompt('Home score',m.home_score??'');if(hs===null)return;const as=prompt('Away score',m.away_score??'');if(as===null)return;const values={home_score:+hs,away_score:+as,status:'pending',submitted_at:new Date().toISOString()};if(online){const {error}=await sb.from('matches').update(values).eq('id',id);if(error){toast(error.message);return}}else{Object.assign(m,values);saveDemo()}toast('Result submitted for confirmation');current=await getTournament(current.id);renderManage('matches')}
async function confirmResult(id){const values={status:'confirmed',confirmed_at:new Date().toISOString()};if(online){await sb.from('matches').update(values).eq('id',id)}else{const m=current.matches.find(x=>x.id===id);Object.assign(m,values);saveDemo()}current=await getTournament(current.id);renderManage('matches')}
async function generateFixtures(){if(current.players.length<2){toast('Add at least 2 players');return}if(current.matches.length&&!confirm('This will create a fresh fixture set. Continue?'))return;const ps=[...current.players];let rows=[];if(current.format==='knockout'){let n=1;while(n<ps.length)n*=2;while(ps.length<n)ps.push({id:null,name:'BYE'});for(let i=0;i<n;i+=2)rows.push({stage:'knockout',round_no:1,position:i/2+1,home_player_id:ps[i].id,away_player_id:ps[i+1].id,status:'scheduled'})}else{for(let i=0;i<ps.length;i++)for(let j=i+1;j<ps.length;j++)rows.push({stage:current.format==='hybrid'?'group':'league',round_no:1,position:rows.length+1,home_player_id:ps[i].id,away_player_id:ps[j].id,status:'scheduled'})}if(online){await sb.from('matches').delete().eq('tournament_id',current.id);const clean=rows.filter(x=>x.home_player_id&&x.away_player_id).map(x=>({...x,tournament_id:current.id}));const {error}=await sb.from('matches').insert(clean);if(error){toast(error.message);return}}else{current.matches=rows.filter(x=>x.home_player_id&&x.away_player_id).map(x=>({id:crypto.randomUUID(),...x}));saveDemo()}current=await getTournament(current.id);renderManage('matches');toast('Fixtures generated')}
window.openJoin=openJoin;window.openManage=openManage;window.renderManage=renderManage;window.submitResult=submitResult;window.confirmResult=confirmResult;window.generateFixtures=generateFixtures;window.share=share;
(async()=>{const hash=location.hash;if(hash.startsWith('#join=')){await openJoin(hash.slice(6));return}renderPublic()})();
